<?php
//-----------------------------------------------------Globals----------------------------------------------------------
//Development mode
$isDevelopment = true;

//-----------------------------------------------Database Connections---------------------------------------------------
//Database Host
$host = '127.0.0.1';

//Database Username
$username = 'root';

//Database Object
$database = 'company';

//Database Password
$password = 'liosD76ambf';

//----------------------------------------------------Pages-------------------------------------------------------------
//Primary home page
$redirectPage = "home.php";

//Login page
$userLogin = "userlogin.html";

//Inventory modifications options listing
$inventoryModificationOptions = 'inventorymodificationhistory.php';

//Inventory display options
$inventoryDisplayOptions = 'inventorydisplay.php';

//Order options
$orderOptions = 'orderoptions.php';




